name: Auto-merge Codex PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Only Codex PRs (or anything with a 'codex' label)
    if: >
      github.event.pull_request.user.login == 'chatgpt-codex-connector[bot]' ||
      contains(toJson(github.event.pull_request.labels), 'codex')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_method: squash
          # optional: wait for checks to pass if you have any
          # required_status_checks: false
